# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\"H\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x1a\n\x12\x63\x61ntidadSolicitada\x18\x03 \x01(\x05\"C\n\x0cProductReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x17\n\x0f\x63\x61ntidadEnviada\x18\x03 \x01(\x05\x32\x36\n\x05Stock\x12-\n\tSendStock\x12\x0f.ProductRequest\x1a\r.ProductReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTREQUEST._serialized_start=15
  _PRODUCTREQUEST._serialized_end=87
  _PRODUCTREPLY._serialized_start=89
  _PRODUCTREPLY._serialized_end=156
  _STOCK._serialized_start=158
  _STOCK._serialized_end=212
# @@protoc_insertion_point(module_scope)
